- name: Create VM in OpenShift
  hosts: localhost
  gather_facts: false
  vars:
    host: "{{ ocp_url }}"
    username: "{{ ocp_user | default(omit) }}"
    password: "{{ ocp_pass | default(omit) }}"
  tasks:

    - name: 
      shell: "oc login --insecure-skip-tls-verify -u {{ocp_user}} -p {{password}} {{ocp_url}} "

    - name: 
      shell: oc whoami --show-token
      register: token

    - name: Create Fedora VM using Kubevirt
      kubevirt.core.kubevirt_vm:
        host: "{{ ocp_url }}"
        api_key: "{{ token.stdout }}"
        state: present
        namespace: my-namespace
        name: "{{ item.name }}"
        spec:
          running: true
          template:
            spec:
              domain:
                devices:
                  interfaces:
                    - name: default
                      masquerade: {}
                  disks:
                    - name: containerdisk
                      disk: {bus: virtio}
                resources:
                  requests:
                    memory: 2Gi
              volumes:
                - name: containerdisk
                  containerDisk:
                    image: quay.io/containerdisks/fedora:latest
      loop: "{{ molecule_yml.platforms }}"

    - name: Wait for SSH to be ready
      wait_for:
        host: "{{ item.address | default('localhost') }}"
        port: 22
        timeout: 300
      loop: "{{ molecule_yml.platforms }}"