---
- name: Destroy VM in OpenShift
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove Fedora VM from OpenShift
      kubevirt.core.kubevirt_vm:
        state: absent
        namespace: my-namespace  # Asegúrate de que coincida con create.yml
        name: "{{ item.name }}"
        wait: yes               # Espera a que se elimine por completo
        wait_timeout: 300
      loop: "{{ molecule_yml.platforms }}"
      ignore_errors: true       # Útil si la VM no llegó a crearse por un error previo

    - name: Clean up associated resources (Optional)
      kubernetes.core.k8s:
        state: absent
        namespace: my-namespace
        kind: "{{ item.kind }}"
        name: "{{ item.name }}"
      loop:
        - { kind: Service, name: "svc-{{ molecule_yml.platforms[0].name }}" }
      ignore_errors: true