dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: fedora-chocolate-smelt-74 # Debe coincidir con el 'hosts' de tu playbook
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: molecule_vars.yml
    host_vars:
      fedora-chocolate-smelt-74:
        ansible_user: fedora
        # Sustituye por la IP que asigne OpenShift o usa el servicio
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy    # Limpia restos de ejecuciones fallidas previas
    - create     # Ejecuta create.yml (Crea la VM en OpenShift)
    - converge   # Ejecuta converge.yml (Lanza tu playbook de JBoss)
    - verify     # Ejecuta verify.yml (Chequea que la app funcione)
    - destroy    # Limpia todo al terminar con éxito